# site settings
title: Akos Paha
email: paha.akos@gmail.com
description: Software Tester
landing-title: Hello, My Name is <span class="name-color"> Akos Paha</span>
# landing-title: Hello, My Name is Akos Paha
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Budapest
state:
zip_code:
country: Hungary
phone:
logo: "/assets/images/logo.ico" # has to be a jpg image

# homepage config
tiles-count: 6
post-tiles: true
projects-tiles: true
home-about: false


theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/akospaha01
  GitLab:
  LinkedIn: https://hu.linkedin.com/in/akos-paha-886273220
  Instagram: https://www.instagram.com/akos_paha
  Twitter: https://twitter.com/akos_paha
  Facebook: https://www.facebook.com/Paha.Akos/
  Slack:

# build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: :path

permalink: pretty
permalink: /:title/

jekyll_admin:
  hidden_links:
    - datafiles

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD